language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

## (Linux only) Use the latest Linux image (Ubuntu Trusty)
dist: trusty

## (OS X only) Use the default OS X image
## See https://docs.travis-ci.com/user/reference/osx#os-x-version
#osx_image: xcode8.3

matrix:
  allow_failures:
    - rust: nightly
    ## For some reason, the beta channel doesn't install on OS X
    - rust: beta
      os: osx

before_install:
  ## Only install clippy on nightly
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then rustup component add clippy-preview; fi
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo clippy --version; fi

script:
  - cd rust
  ## Only run clippy on nightly
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo clippy; fi
  - cargo build --verbose
  - cargo test --verbose

notifications:
  irc:
    channels:
      - "irc.oftc.net#tor-ci"
    template:
      - "%{repository} %{branch} %{commit} - %{author}: %{commit_subject}"
      - "Build #%{build_number} %{result}. Details: %{build_url}"
    on_success: change
    on_failure: change
  email:
    on_success: never
    on_failure: change
